version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=gampUser
      - POSTGRES_USER=gamp
      - POSTGRES_PASSWORD=gamp-pass
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql